ServiceManager/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^servicemanager/', include('pages.urls', namespace='pages')),
    url(r'^servicemanager/institutions/', include('institution.urls', namespace='institutions'))
]

pages/urls.py
from django.conf.urls import url, patterns
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='pages/index.html'), name='index'),
    url(r'^signup/$', TemplateView.as_view(template_name='pages/signup.html'), name='signup'),
    url(r'^personal/$', TemplateView.as_view(template_name='pages/personal.html'), name='personal'),
)

pages/templates/pages/create_perfil.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%  trans 'Service Manager' %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.5/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'pages/main.css' %}"/>

    <script src="{% static 'jquery-2.1.4/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap-3.3.5/js/bootstrap.min.js' %}"></script>
</head>
<body class="background-secondary">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1>Perfil of institution</h1>
                <div>
                    <form>
                        <label>Institution name:</label>
                        <input type="text"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'pages/create_perfil.js' %}"></script>
</body>
</html>

pages/templates/pages/index.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%  trans 'Service Manager' %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.5/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'pages/main.css' %}"/>

    <script src="{% static 'jquery-2.1.4/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap-3.3.5/js/bootstrap.min.js' %}"></script>
</head>
<body class="background-secondary">
    <div  ng-app="searchApp">
        <div class="container" ng-controller="serviceController">
            <div class="row">
                <h1>{% trans 'Service Catalog ' %}</h1>
            </div>
            <div class="row">
                <div class="pull-right col-lg-5">
                    <div class="col-lg-2">
                        <p><a href="/universaluser/authentication/index/?next={% url 'pages:personal' %}" class="btn btn-default">{% trans 'sign in' %}</a></p>
                    </div>
                    <div class="col-lg-2">
                        <p><a href="{% url 'pages:signup' %}" class="btn btn-primary">{% trans 'sign up' %}</a></p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-7">
                    <div class="row">
                        <h2>{% trans 'Search' %}</h2>
                    </div>
                    <div class="row">
                        <input type="text" class="form-control" placeholder="{% trans 'search for a service or institution' %}"/>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="row">
                        <h2>{% trans 'Institutions' %}</h2>
                    </div>
                    <div class="row">
                        <div class="well well-lg highlight" ng-repeat="institution in institutions">
                            <div ng-click="openLinks(institution)">
                                <h3>{$ institution.name $} - {$ institution.initials $}</h3>
                                <p>{$ institution.description $}</p>
                            </div>
                            <div ng-if="institution.links && institution.activated">
                                <h4>List of links:</h4>
                                <ul class="list-group">
                                    <li class="list-group-item highlight" ng-repeat="link in institution.links">
                                        <div ng-click="openServices(institution, $index, link)">
                                            <h5><b>{$link.name$}: </b><a href="{$ link.url $}">{$ link.url $}</a></h5>
                                        </div>
                                        <ul class="list-group" ng-if="link.services && link.activated">
                                            <li class="list-group-item highlight" ng-repeat="service in link.services">
                                                <h6><b>{$ service.name $}: </b><a href="{$service.url$}">{$ service.url $}</a></h6>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!--
                        <div class="well well-lg highlight">
                            <h3>IBAMA</h3>
                            <p>Cuidando da nossa fauna e flora</p>
                        </div>
                        <div class="well well-lg highlight">
                            <h3>INPE</h3>
                            <p>Trabalhando com novas pesquisas</p>
                        </div>
                        <div class="well well-lg highlight">
                            <h3>ANA</h3>
                            <p>Árvores everywhere</p>
                        </div> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'angular/angular.min.js' %}"></script>
    <script src="{% static 'pages/auth.js' %}"></script>
    <script src="{% static 'pages/main.js' %}"></script>
</body>
</html>

pages/templates/pages/personal.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{%  trans 'Personal page' %}</title>
        <link rel="stylesheet" href="{% static 'bootstrap-3.3.5/css/bootstrap.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'pages/main.css' %}"/>

        <script src="{% static 'jquery-2.1.4/jquery.min.js' %}"></script>
        <script src="{% static 'bootstrap-3.3.5/js/bootstrap.min.js' %}"></script>
    </head>
    <body class="background-secondary" ng-app="personalApp">
        <div>
            <div class="container" ng-controller="personalController">
                <div class="row">
                    <h1>{$ institution.name $}</h1>
                </div>
                <div class="row">
                    <div class="col-lg-7">
                        <div class="row">
                            <h3>Links of services:</h3>
                            <ul class="list-group">
                                <li class="list-group-item" ng-repeat="link in institution.links">
                                    <b>{$ link.name $} :</b> {$ link.url $}
                                    <button class="pull-right close" ng-click="deleteServiceLink($index, link)">&times;</button>
                                </li>
                            </ul>
                            <div class="input-group">
                                <label>Name</label>
                                <input type="text" class="form-control" ng-model="name" placeholder="Type here the name to the link"/>
                            </div>

                            <div class="">
                                <label>Link</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" ng-model="new_link" placeholder="Type here the link to your API"/>
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" ng-click="addServiceLink()">Add API link</button>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div>
                                <h3>My remote API:</h3>
                            </div>
                            <div>
                                <div class="input-group" ng-if="container == null" >
                                    <input type="text" class="form-control" ng-model="container_name" placeholder="Type here the name to your API"/>
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" ng-click="createAPI(container_name)">Create an API</button>
                                    </span>
                                </div>
                            </div>
                            <div ng-if="container != null">
                                <h4>Links:</h4>
                                <ul class="list-group">
                                    <li class="list-group-item"><b>API: </b>{$ container.api_link $}<a class="pull-right close" href="{$ container.api_link $}" ><span class="glyphicon glyphicon-globe"></span></a></li>
                                    <li class="list-group-item"><b>Geonode: </b>{$ container.geonode_link $}<a class="pull-right close" href="{$ container.geonode_link $}"><span class="glyphicon glyphicon-globe"></span></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src="{% static 'angular/angular.min.js' %}"></script>
        <script src="{% static 'pages/auth.js' %}"></script>
        <script src="{% static 'pages/personal.js' %}"></script>
    </body>
</html>

pages/templates/pages/signup.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{%  trans 'Sign up' %}</title>
        <link rel="stylesheet" href="{% static 'bootstrap-3.3.5/css/bootstrap.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'pages/main.css' %}"/>

        <script src="{% static 'jquery-2.1.4/jquery.min.js' %}"></script>
        <script src="{% static 'bootstrap-3.3.5/js/bootstrap.min.js' %}"></script>
    </head>
    <body class="background-secondary">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <h1>Sign up</h1>
                    <p>
                        To sign up in this site, please send a email to idehco3@gmail.com with the following information:
                    </p>
                    <ul class="list-group">
                        <li class="list-group-item">Name of institution</li>
                        <li class="list-group-item">Name of leader of institution</li>
                        <li class="list-group-item">CNPJ</li>
                    </ul>
                </div>
            </div>
        </div>
    </body>
</html>